meta_product_name: "Medi+Safe"
meta_title: "Medi+Safe - Everyone must to be safe!"
meta_description: "Helping nurses to create their own schedules."
# meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
